[package]
  cjc-version = "1.0.0"
  name = "stdx"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = "src/stdx"
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
